//UNITS
export const CHECK_LOGIN_START = 'api/CHECK_LOGIN_START';
export const CHECK_LOGIN_SUCCESS = 'api/CHECK_LOGIN_SUCCESS';
export const CHECK_LOGIN_FAIL = 'api/CHECK_LOGIN_FAIL';

//Product Listing
export const PRODUCT_LISTING_START = 'api/PRODUCT_LISTING_START';
export const PRODUCT_LISTING_SUCCESS = 'api/PRODUCT_LISTING_SUCCESS';
export const PRODUCT_LISTING_FAIL = 'api/PRODUCT_LISTING_FAIL';

//Product Edit
export const PRODUCT_EDIT_START = 'api/PRODUCT_EDIT_START';
export const PRODUCT_EDIT_SUCCESS = 'api/PRODUCT_EDIT_SUCCESS';
export const PRODUCT_EDIT_FAIL = 'api/PRODUCT_EDIT_FAIL';

//Product Delete
export const PRODUCT_DELETE_START = 'api/PRODUCT_DELETE_START';
export const PRODUCT_DELETE_SUCCESS = 'api/PRODUCT_DELETE_SUCCESS';
export const PRODUCT_DELETE_FAIL = 'api/PRODUCT_DELETE_FAIL';

//Product Add
export const PRODUCT_ADD_START = 'api/PRODUCT_ADD_START';
export const PRODUCT_ADD_SUCCESS = 'api/PRODUCT_ADD_SUCCESS';
export const PRODUCT_ADD_FAIL = 'api/PRODUCT_ADD_FAIL';

//Product Add
export const PRODUCT_SEARCH_START = 'api/PRODUCT_SEARCH_START';
export const PRODUCT_SEARCH_SUCCESS = 'api/PRODUCT_SEARCH_SUCCESS';
export const PRODUCT_SEARCH_FAIL = 'api/PRODUCT_SEARCH_FAIL';

//Add
export const ADD_STATUS = 'ADD_TO_STATUS';
